FROM node:alpine AS build
WORKDIR /app
COPY ./frontend/. .
COPY .env .
RUN npm i -g pnpm &&\
    pnpm install --frozen-lockfile &&\
    set -a && . ./.env && set +a &&\
    if [ -n "$PUBLIC_FRONTEND_URL" ] && [ "$PRIVATE_ALLOW_SEARCH_INDEXING" = "true" ]; then printf 'User-agent: *\nAllow: /\n\nSitemap: %s/sitemap.xml\n' "$PUBLIC_FRONTEND_URL" > static/robots.txt; else printf 'User-agent: *\nDisallow: /\n' > static/robots.txt; fi &&\
    pnpm run build -- --mode production &&\
    pnpm install --prod --ignore-scripts

FROM node:alpine
USER node:node
WORKDIR /app
COPY --from=build --chown=node:node /app/build ./build
COPY --from=build --chown=node:node /app/node_modules ./node_modules
COPY --from=build --chown=node:node /app/package.json .
HEALTHCHECK --interval=10s \
    CMD wget --no-verbose --tries=1 --spider "http://127.0.0.1:3000/healthcheck" || exit 1
CMD ["node", "./build"]
