# Generated by Django 4.0.2 on 2022-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='box_art',
            field=models.URLField(null=True),
        ),
    ]
