# Generated by Django 3.2.9 on 2021-12-01 22:22

import archiv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vod',
            fields=[
                ('uuid', models.SlugField(default=archiv.models.gen_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('filename', models.SlugField()),
            ],
        ),
    ]
