# Generated by Django 3.2.9 on 2021-12-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0002_auto_20211202_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vod',
            old_name='format_note',
            new_name='format_id',
        ),
    ]
