# Generated by Django 3.2.9 on 2021-12-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0004_auto_20211202_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vod',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
