# Generated by Django 3.2.9 on 2021-12-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0005_alter_vod_fps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcaster_id', models.SlugField()),
                ('ttv_client_id', models.SlugField()),
                ('ttv_client_secret', models.SlugField()),
                ('ttv_bearer', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('url', models.URLField()),
                ('provider', models.SlugField()),
            ],
        ),
    ]
