# Generated by Django 3.2.9 on 2021-12-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0006_apistorage_emote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apistorage',
            old_name='ttv_bearer',
            new_name='ttv_bearer_token',
        ),
    ]
