# Generated by Django 3.2.9 on 2021-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0007_rename_ttv_bearer_apistorage_ttv_bearer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistorage',
            name='ttv_bearer_token',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
