# Generated by Django 3.2.9 on 2021-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0008_alter_apistorage_ttv_bearer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emote',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
