# Generated by Django 3.2.9 on 2021-12-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0009_emote_outdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emote',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
