# Generated by Django 3.2.9 on 2021-12-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0010_alter_emote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistorage',
            name='date_emotes_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apistorage',
            name='date_vods_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
