# Generated by Django 4.0 on 2021-12-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0011_auto_20211207_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='apistorage',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
