# Generated by Django 4.0 on 2021-12-12 08:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0012_apistorage_is_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 12, 12, 8, 49, 27, 408740, tzinfo=utc))),
                ('raw', models.TextField()),
            ],
        ),
    ]
