# Generated by Django 4.0 on 2021-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0014_alter_chatmessage_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apistorage',
            name='broadcaster_id',
            field=models.SlugField(default='108776574'),
        ),
    ]
