# Generated by Django 4.0.1 on 2022-01-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0016_remove_vod_bitrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
