# Generated by Django 4.0.1 on 2022-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0017_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vod',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
